install_packages <- function() {
  
  install.packages("parallel", quiet = TRUE)
  install.packages("tinytex", quiet = TRUE)
  install.packages("ggh4x", quiet = TRUE)
  install.packages("vegan", quiet = TRUE)
  install.packages("devtools", quiet = TRUE)
  install.packages("openxlsx", quiet = TRUE)
  install.packages("ape", quiet = TRUE)
  install.packages("ggtext", quiet = TRUE)
  install.packages("cowplot", quiet = TRUE)
  install.packages("RColorBrewer", quiet = TRUE)
  install.packages("glue", quiet = TRUE)
  install.packages("lubridate", quiet = TRUE)
  install.packages("scales", quiet = TRUE)
  install.packages("viridis", quiet = TRUE)
  install.packages("ggrepel", quiet = TRUE)
  install.packages("ggforce", quiet = TRUE)
  install.packages("config", quiet = TRUE)
  install.packages("yaml", quiet = TRUE)
  install.packages("colorspace", quiet = TRUE)
  install.packages("jsonlite", quiet = TRUE)
  install.packages("BiocManager", quiet = TRUE)
  install.packages("castor", quiet = TRUE)
  install.packages("seqinr", quiet = TRUE)
  
  suppressMessages(library(BiocManager))
  suppressMessages(BiocManager::install("phyloseq", quiet = TRUE, update = TRUE, ask = FALSE))
  suppressMessages(BiocManager::install("decontam", quiet = TRUE, update = TRUE, ask = FALSE))
  
  suppressMessages(library(devtools))
  suppressMessages(devtools::install_github("stijnteunissen/micromics", quiet = TRUE))
  
  suppressMessages(BiocManager::install(
    c("SparseArray", "DelayedArray", "S4Arrays", "SummarizedExperiment", "SingleCellExperiment", "TreeSummarizedExperiment", "treeio", "microbiome"),
    quiet = TRUE, update = TRUE, ask = FALSE
  ))
  
  suppressMessages(devtools::install_github("jbisanz/qiime2R", quiet = TRUE))
  suppressMessages(devtools::install_github(repo = "wu-lab-uva/RasperGade", quiet = TRUE))
  suppressMessages(devtools::install_github(repo = "wu-lab-uva/RasperGade16S", quiet = TRUE))
  
  suppressMessages(library(qiime2R))
  suppressMessages(library(micromics))
  suppressMessages(library(parallel))
  suppressMessages(library(tinytex))
  suppressMessages(library(ggh4x))
  suppressMessages(library(vegan))
  suppressMessages(library(qiime2R))
  suppressMessages(library(tidyverse))
  suppressMessages(library(openxlsx))
  suppressMessages(library(ape))
  suppressMessages(library(ggtext))
  suppressMessages(library(cowplot))
  suppressMessages(library(RColorBrewer))
  suppressMessages(library(decontam))
  suppressMessages(library(glue))
  suppressMessages(library(lubridate))
  suppressMessages(library(scales))
  suppressMessages(library(viridis))
  suppressMessages(library(ggrepel))
  suppressMessages(library(ggforce))
  suppressMessages(library(config))
  suppressMessages(library(yaml))
  suppressMessages(library(dplyr))
  suppressMessages(library(phyloseq))
  suppressMessages(library(colorspace))
  suppressMessages(library(jsonlite))
  suppressMessages(library(bbmle))
  suppressMessages(library(stats4))
  suppressMessages(library(pracma))
  suppressMessages(library(RasperGade))
  suppressMessages(library(RasperGade16S))
  
  message("All packages have been installed and loaded.")
}
